### ISSUE TITLE
Unit cell => Translation Axes

### ISSUE THREAD

**Issue by ghutchis** [OpenChemistry/chemicaljson#11]
Currently, the unit cell is written as alpha, beta, gamma, a, b, c. But this is 6 degrees of freedom, but many solid state codes use translation vectors.

For use with solid-state codes, it would be ideal if CJSON:
- Always wrote out real-space Cartesian coordinates (in addition to fractional)
- Wrote out the 3x3 translation matrix either in addition to the unit cell parameters or instead of the parameters.

Otherwise, it's hard to implement CP2K or VASP or ABINIT input generators in Avo2 (among other things)

**Comment by harsh07051** [comment]
I will like to fix  this issue

**Comment by ghutchis** [comment]
This is actually already fixed in `avogadrolibs`, e.g.



[TePb.txt](https://github.com/OpenChemistry/chemicaljson/files/5430023/TePb.txt)
