### ISSUE TITLE
Consider writing a json schema file

### ISSUE THREAD

**Issue by ericoporto** [OpenChemistry/chemicaljson#14]
https://github.com/tangram-js/json-schema-editor
https://json-schema.org/

Not sure if relevant, if it's not, please close this issue.

**Comment by ghutchis** [comment]
I'm adding this to the (long) todo. I just discovered https://jsontopydantic.com which should help formalize this.

Certainly it's needed before Avogadro 2 is released. 😄

**Comment by ghutchis** [comment]
I'll put up a pull request tomorrow, but here's a draft:
https://gist.github.com/ghutchis/3a31e5b597dafb15de9ea048cad35268#file-cjson-schema

**Comment by ghutchis** [comment]
Thanks for the push...
